### ISSUE TITLE
Duplicate expect have_content seems to fail while waiting

### ISSUE THREAD

**Issue by davidwparker** [teamcapybara/capybara#1824] opened 2017-01-03 20:26 UTC
## Meta
Capybara Version:
2.4.4

Driver Information:
selenium-webdriver 3.0.5
Firefox 50.1.0

## Expected Behavior
I should be able to have duplicate `expect(page).to have_content("content")` statements, with `click_on "button"` in between, and another `click_on "button 2"` after, and it should click the 2nd button ok.

## Actual Behavior
The 2nd `click_on` (`click_on "button 2"`) doesn't work every time. It seems like half the time it works, and half the time it just hangs.

## Steps to reproduce
Doesn't work:
```ruby
    expect(page).to have_content("Shelby Mustang GT")

    click_on "+ Relationship"
    expect(page).to have_content("Shelby Mustang GT")

    # This button doesn't end up getting clicked every time:
    click_on "Manage Relationships"
```

_Seems to be_ working every time:
```ruby
    expect(page).to have_content("Shelby Mustang GT")

    click_on "+ Relationship"
    expect(page).to have_content("Relationship successfully added")

    # now it works...
    click_on "Manage Relationships"
```

HTML for "Shelby Mustang GT"
```html
<h1 class="item-name">Shelby Mustang GT</h1>
```

HTML for "Relationship successfully added"
```html
<div class="alert alert-success alert-dismissable">
      Relationship successfully added
      <button aria-hidden="true" class="close" data-dismiss="alert" type="button">×</button>
    </div>
```

HTML for "Manage Relationships"
```html
<a class="btn btn-primary btn-sm" rel="nofollow" href="/catalog_items/shelby-mustang-300sl-2f1e501e-04bc-4eb9-b457-f078795e22eb/related_catalog_items">Manage Relationships</a>
```

Note that `click_on "Manage Relationships"` is also used earlier and it does work.

Also, if I throw a `sleep 1` above `click_on "Manage Relationships"` when I do have duplicate `have_content` statements, it seems to work as well. It appears something is up with the async code thinking it already worked so it doesn't let the second statement perform it's async waiting?

Thanks!

**Comment by abotalov** [comment] 2017-01-03 21:35
What do you mean by "doesn't work" / "hangs"? Do you see any error?

**Comment by davidwparker** [comment] 2017-01-03 21:48
Yes, apologies. It fails on the line after `click_on "Manage Relationships`:

```ruby
    within ".catalog-item-search-results", text: "Shelby Mustang GT" do
      click_on "Remove Relationship"
    end
```

(which passes ok on either using `sleep` or changing the latter `have_content`)

**Comment by twalpole** [comment] 2017-01-03 21:57
This sounds like it might be expected behavior depending on exactly what clicking on "+ Relationship" does.  `click_on` just clicks the button, it doesn't wait for anything to happen since it has no idea what is going to happen (and hence no idea how to wait for it).  This means if you check for the content "Shelby Mustang GT", click on "+ Relationship", and then check for the content "Shelby Mustang GT" again it's possible the second content check will match the same element the first content check did because any side effects of click_on haven't occurred yet.  That's why you need to check for visual things that are not on the page before you trigger an action but are after the action.  Checking for "Relationship successfully added" works reliably because it's not on the page until the action completes (and sleep just works because it delays until well past the time when the action has completed).

Closing this now, if you can provide more details on this that shows it's not expected behavior we can reopen.

**Closed by twalpole** 2017-01-03 21:57 UTC

**Comment by davidwparker** [comment] 2017-01-03 22:02
Thanks @twalpole - I'm not entirely sure of the expected behavior yet (I just inherited this codebase and I don't have anyone that I can ping questions to). I'll continue to explore it and if it turns out to be unexpected, then I'll be back. Thanks for the follow up- that makes sense to me!
