### ISSUE TITLE
Compatibility with puma v6

### ISSUE THREAD

**Issue by ShockwaveNN** [teamcapybara/capybara#2590] opened 2022-10-14 06:18 UTC
## Meta
Capybara Version:
3.37.1
Driver Information (and browser if relevant):
selenium-webdriver (4.5.0) with Google Chrome  106.0.5249.119

## Actual Behavior
Checking the latest version of puma (v6) released yesterday
Running my test suite causing
```
     Failure/Error: events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio

     NoMethodError:
       undefined method `stdio' for Puma::Events:Class

         events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio
                                                                                 ^^^^^^
     # /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:32:in `block in <top (required)>'
     # /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara.rb:253:in `run_default_server'
     # /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:4:in `block in <top (required)>'
     # /opt/hostedtoolcache/Ruby/3.1.2/x64/lib/ruby/gems/3.1.0/gems/capybara-3.37.1/lib/capybara/server.rb:77:in `block in boot'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
     ```

**Comment by davidrunger** [comment] 2022-10-14 06:56
I am seeing a similar error with puma 6.0.0, although the error is slightly different in my case, because I have set `conf.options[:Silent]` to `true` in my tests (via `Capybara.server = :puma, { Silent: true }` in `spec/spec_helper.rb`). So the error I am seeing is coming from the other part of the ternary:

```
Failure/Error: events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio

          NoMethodError:
            undefined method `strings' for Puma::Events:Class

              events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio
                                                             ^^^^^^^^
          # /home/runner/work/david_runger/david_runger/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:32:in `block in <top (required)>'
          # /home/runner/work/david_runger/david_runger/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/config.rb:64:in `block in server='
          # /home/runner/work/david_runger/david_runger/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/server.rb:77:in `block in boot'
          # 
          #   Showing full backtrace because every line was filtered out.
          #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
          #   RSpec::Configuration#backtrace_inclusion_patterns for more information.
```

**Comment by davidrunger** [comment] 2022-10-14 07:24
I think that this is the PR https://github.com/puma/puma/pull/2798 that introduced this bug (specifically, this commit https://github.com/puma/puma/commit/8a4ef0c) by removing the `Puma::Events.strings` and `Puma::Events.stdio` methods (here: https://github.com/puma/puma/commit/8a4ef0c#diff-3d469ea387dd7c1a10a5b143d8b02afb6d4d2a9a0b7a5532b88ab5d17014fdbcL164-L170).

Looking at those changes, it appears that the methods were essentially moved to the new `Puma::LogWriter` class, i.e. as `Puma::LogWriter.strings` and `Puma::LogWriter.stdio`, with corresponding changes to the method bodies (here: https://github.com/puma/puma/commit/8a4ef0c#diff-49c664eec56eb4d3549b03b2a5e73e72714f0fb119610aa398cfd6feda70d4efR44-R50).

**Comment by elalemanyo** [comment] 2022-10-14 09:29
@davidrunger with your version everything works 🥳 Maybe you can create a PR.
Thanks!

**Comment by ShockwaveNN** [comment] 2022-10-14 09:32
@elalemanyo I think @davidrunger mention that merging this break compatibility with someone using Puma v5, don't think this is a good idea

**Comment by elalemanyo** [comment] 2022-10-14 09:34
@ShockwaveNN maybe this could be a new capybara release? or what is your suggestion?

**Comment by ShockwaveNN** [comment] 2022-10-14 09:38
@elalemanyo I think we should wait for the maintainers option on this question

Or refactor @elalemanyo patch to have compatibility with older puma versions

Because introducing hard lock on v6 on newer version of capybara may raise a lot of negative feedback

**Comment by elalemanyo** [comment] 2022-10-14 10:30
@ShockwaveNN Maybe something like this: https://github.com/teamcapybara/capybara/compare/master...elalemanyo:capybara:master

**Comment by ShockwaveNN** [comment] 2022-10-14 10:48
@elalemanyo Yeah I think so, a little not-straight forwarding, maybe extract something to methods, little less spagetty-code

**Comment by stevehill1981** [comment] 2022-10-15 11:12
> Or refactor @elalemanyo patch to have compatibility with older puma versions

It'd be a bit messy, but the original code already refers to `Puma::Const::PUMA_VERSION` - so we could switch approaches based on that. It would maintain compatibility with Puma < 6 whilst still supporting the new release.

Confirmed that the patch as is works fine, either way.

**Comment by elalemanyo** [comment] 2022-10-15 14:47
@stevehill1981 @ShockwaveNN Using the inspiration from @MSP-Greg I have tried to improve the code

**Comment by twalpole** [comment] 2022-10-15 23:13
Closed via https://github.com/teamcapybara/capybara/pull/2592

**Closed by twalpole** 2022-10-15 23:13 UTC

**Comment by ShockwaveNN** [comment] 2022-10-16 06:29
@twalpole Are you sure? Fix in 2592 looking very different from error in this issue?

**Comment by davidrunger** [comment] 2022-10-16 06:31
@ShockwaveNN I believe that @twalpole meant to link this PR: https://github.com/teamcapybara/capybara/pull/2530.

**Comment by ShockwaveNN** [comment] 2022-10-16 06:34
@davidrunger Yeah thanks, this looks like it )
