### ISSUE TITLE
Capybara finds and (tries) to click on hidden elements

### ISSUE THREAD

**Issue by dwt** [teamcapybara/capybara#1856] opened 2017-04-28 09:26 UTC
## Meta
Capybara Version: capybara (2.10.1)
Driver Information (and browser if relevant):
Firefox 53.0 (64-Bit), (venv:yeepa), geckodriver 0.16.1

## Expected Behavior
Hidden page elements should neither be found, nor be clicked on - especially if the element is behind other elements and the click therefore is on a completely different element.

## Actual Behavior
A hidden element is found and selenium clicks on any random element that is where it thinks the hidden element might be.

## Steps to reproduce
```ruby
require 'capybara'

Capybara.run_server = false
Capybara.default_max_wait_time = 20
Capybara.ignore_hidden_elements = true
Capybara.exact = false
Capybara.match = :prefer_exact


Capybara.register_driver(:firefox) do |app|
  Capybara::Selenium::Driver.new(app, browser: :remote, 
    desired_capabilities: Selenium::WebDriver::Remote::Capabilities.firefox)
end

Capybara.default_driver = :firefox

page = Capybara::Session.new(:selenium)
page.visit('https://test.yeepa.de/auth/login/token?login_token=2%7C1%3A0%7C10%3A1493366171%7C20%3Alogin_token_for_user%7C4%3ANDI3%7Cbc94154597db08d5a093a55f0d392614ec89c78a7895a17acb643098d30a5d71')

page.click_link("Overview")
puts 'this actually clicked on "Measure" instead of raising "element not found" as the "measure" submenu is initially hidden'
sleep 2
```

This bug is being re-raised here, after discussion with the selenium guys here: https://github.com/SeleniumHQ/selenium/issues/3936 . Please take the discussion there into consideration.

**Comment by twalpole** [comment] 2017-04-28 17:33
There are a number of things here.  

In the selenium issue you linked to there is a comment talking about the error name changing, and that is true.  Unfortunately selenium-webdriver 3.4.0 added those errors in a non-backwards compatible manner and made a naming error when adding support for those errors so they would never actually be raised - https://github.com/SeleniumHQ/selenium/issues/3878.  A fix for the naming error has been committed to selenium-webdriver but until 3.4.1 (or whatever the next release is) those new errors will never actually be reported.   Since they were added in a non BC manner, Capybara only has support for those errors in its master branch currently (and has a workaround for the misnaming too) so if the problem was actually caused by the new errors then using the master branch should fix it.  However, the real issue here is not the new errors, it's the fact that the `displayed?` method in selenium-webdriver 3.4.0 with geckodriver 0.16.1 appears to be fully broken.  You can see that by calling 

    l = page.find_link('Overview')
    puts l.native.displayed?

before your `click_link`.  All that is doing is calling the selenium-webdriver Selenium::WebDriver::Element#displayed? method, which returns `true` which is obviously incorrect for the page.

**Comment by twalpole** [comment] 2017-04-28 18:06
After looking a bit deeper, it's actually the "Overview" link in the side menu (not top menu) that it's finding.  That submenu appears to be hidden by pushing it off the screen rather than `display:none` (the top menu is display: none) and may be why it's being considered visible.  Try the Capybara master branch and see if that makes a difference

**Comment by twalpole** [comment] 2017-04-28 23:31
Closing since these issues are not Capybara issues.  They are either selenium-webdriver or geckodriver issues. 

1.  An element hidden behind another element via z-index is reported as visible -  This may technically be spec compliant, needs reading of the WebDriver spec - https://www.w3.org/TR/webdriver/#element-displayedness - to determine 
2.  A click called on an element hidden another element via z-index does not generate an error - it does with chromedriver, so most likely a geckodriver issue

**Closed by twalpole** 2017-04-28 23:31 UTC
