### ISSUE TITLE
jstree + capybara 3.6 + drag_to no longer wroks

### ISSUE THREAD

**Issue by JunichiIto** [teamcapybara/capybara#2235] opened 2019-07-30 10:30 UTC
## Meta
Capybara Version: 3.6.0 or higher
Driver Information (and browser if relevant): selenium-webdriver 3.142.3 with Chrome 75.0.3770.142

## Expected Behavior

The following drag and drop demo with [jstree](https://github.com/vakata/jstree) should work.

https://gist.github.com/JunichiIto/2ec9caf56a09acb2ef66191669988b52

## Actual Behavior

The demo works with capybara 3.5.1. But switching to capybara 3.6.0 or latest(3.27.0) by editing line 9-11, it won't work. The element "A" is selected, but won't move.

I read the following issues, but could not resolve my problem:

- [Chrome 75\+ drag\_to no longer works · Issue \#2223 · teamcapybara/capybara](https://github.com/teamcapybara/capybara/issues/2223)
- [Drag and drop tests stop working in 3\.6\.0\+ · Issue \#2098 · teamcapybara/capybara](https://github.com/teamcapybara/capybara/issues/2098) 

## Steps to reproduce

```
ruby jstree_test.rb
```

**Comment by twalpole** [comment] 2019-07-30 14:45
The problem is that all the different drag/drop libraries look for different sets of events to do their dragging and dropping.  I don't know what jstree is expecting but I'll try and take a look later today/this week

**Comment by twalpole** [comment] 2019-07-30 15:56
@JunichiIto  When dragging, Capybara attempts to determine whether the page is using legacy dragging (mouse down, move, up, etc events) or HTML5 dragging (dragstart, drag, etc events) so that it can emulate HTML5 dragging when necessary (because chromedriver, geckodriver, etc don't generate the HTML5 events). It detects the need for HTML5 based on whether or not the mousedown event is defaultPrevented and whether or not the element being dragged (or an ancestor) has the `draggable = true` property (HTML5 draggable).  The issue here is we're not seeing the mousedown being defaultPrevented, and jstree is building it's structure using &lt;a> elements which are by default HTML5 draggable, however jstree uses legacy dragging.  

A short term fix for your tests would be to set the  HTML5 `draggable` property on all the &lt;a> elements in the tree to false before dragging which in your example would look like

    occasion_li_1 = sess.find('#j1_1_anchor')
    occasion_li_2 = sess.find('#j1_2_anchor')
    sess.execute_script("$('#container a').each(function(){ this.draggable = false })")
    occasion_li_1.drag_to(occasion_li_2)

This will then trigger `drag_to` to use the legacy dragging mode.  Longer term I'm considering adding an override option to `drag_to` in order to be able to force legacy or HTML5 dragging mode.

**Comment by twalpole** [comment] 2019-07-30 16:50
You can also try the `jstree` branch of this repo  - and see if that works for you.

**Comment by twalpole** [comment] 2019-07-30 20:24
Closed via de62b4ff9b5a57045e462e9c246429d43a4852d9

**Closed** 2019-07-30 23:54 UTC

**Comment by JunichiIto** [comment] 2019-07-31 02:11
@twalpole Great, `jstree` branch works for me! Thank you very much for your quick fix.
