### ISSUE TITLE
StaleElementReferenceError consistently showing on element lookup on iOS

### ISSUE THREAD

**Issue by ragog** [teamcapybara/capybara#2177] opened 2019-04-17 10:05 UTC
## Meta
Capybara Version: 3.16.2
Running against Sauce Labs RDC, Appium version 1.12.0
Code for repro: [Ruby-Cucumber-Capybara.zip](https://github.com/teamcapybara/capybara/files/3088936/Ruby-Cucumber-Capybara.zip)

## Expected Behavior
Test runs successfully for rake task `iphone` or `ipad` (`bundle exec cucumber features/remove_from_cart.feature`)

## Actual Behavior
Test always fails with StaleElementReferenceError on element lookup. Logs: 
[sample-failing.log](https://github.com/teamcapybara/capybara/files/3088948/sample-failing.log)

## Steps to reproduce
1. export environment variable `SAUCE_API_KEY`
2. Run `rake iphone`

## Notes:
- as per @titusfortner suggestion, setting env variable `DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS` to true solves the issue, and the test passes reliably without trace of StaleElementReferenceError (see logs: 
[sample-passing.log](https://github.com/teamcapybara/capybara/files/3089013/sample-passing.log))

**Comment by twalpole** [comment] 2019-04-17 15:05
Thanks for the reproduction case, unfortunately I don't have access to a SAUCE_API_KEY with which to debug this with.  @titusfortner and I chatted about this yesterday and it appears to me as if the error is in the appium drivers element serialization during the `execute_script` command.  The elements are definitely being found, they are on a page which isn't dynamically changing, but immediately after finding they are being reported as not being there.  My guess is the mobile safari driver is expecting elements referenced by the w3c spec'd key of 'element-6066-11e4-a52e-4f735466cecf' but is being passed a key of 'ELEMENT' - Without access to a valid SAUCE_API_KEY I can't really confirm that though.

**Comment by twalpole** [comment] 2019-04-17 15:42
Another potential cause would be if the appium driver doesn't support receiving an array of elements as an argument to execute_script but rather only single elements.

**Comment by twalpole** [comment] 2019-04-17 19:57
After looking at the success log and seeing that there are successful calls to execute scripts receiving one element as an arg, I'm leaning towards this being an issue where the appium driver incorrectly doesn't accept an array of elements as an argument for script execution.  Again, without an api key to verify this I can't be 100% sure, but I am 90+% sure that's the issue.  I'm not really sure who would be responsible for fixing that behavior. @titusfortner do you have info on the responsible people? The current master branch of Capybara will silently hide the error but it would be more efficient if the issue was fixed in appium.

**Comment by twalpole** [comment] 2019-04-18 19:14
@ragog I believe Capybara 3.17.0 should mask this error - but it would be MUCH better if Appium fixed the `execute_script` in their driver to support arrays of elements as dictated by the WebDriver spec (I'm assuming that is the root cause of the issue).  Do you have any idea who to contact about that?

**Comment by twalpole** [comment] 2019-04-19 23:28
I've filed an issue on the appium repo for this - https://github.com/appium/appium/issues/12522 - Until I get information otherwise I'm considering this not to be a Capybara issue.

**Closed by twalpole** 2019-04-19 23:28 UTC

**Comment by twalpole** [comment] 2019-04-22 18:21
There is an approved PR that should fix this in appium-ios-driver - https://github.com/appium/appium-ios-driver/pull/372 - Hopefully that will be in the next appium release and this issue should go away

**Comment by ragog** [comment] 2019-04-23 08:47
Looks good @twalpole, thank you for the quick response.
