### ISSUE TITLE
Edge Browser not identifying the Elements in Selenium

### ISSUE THREAD

**Issue by kishorekumartbm** [teamcapybara/capybara#2293] opened 2019-12-31 10:55 UTC
I am using Selenium and Ruby to do automation testing and using Edge browser to launch the browser. Using Capybara as the wrapper.

## Meta
Capybara Version: 3.19
Selenium WebDriver : 3.141.0
Edge : 44.17763.831.0

## Expected Behavior
It has to launch the application in the Edge browser and perform the user actions like Click, Sendkeys etc.,

## Actual Behavior
It is launching the Edge browser and not performing any user action.
Throws the below error.

Traceback (most recent call last):
        21: from ./selenium-edge-capy.rb:1:in `each'
        20: from ./selenium-edge-capy.rb:1:in `each'
        19: from ./selenium-edge-capy.rb:1:in `each'
        18: from ./selenium-edge-capy.rb:1:in `each'
        17: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.29.0/lib/capybara/result.rb:32:in `block in initialize'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.29.0/lib/capybara/queries/selector_query.rb:105:in `matches_filters?'
        15: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.29.0/lib/capybara/queries/selector_query.rb:416:in `matches_system_filters?'
        14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.29.0/lib/capybara/queries/selector_query.rb:515:in `matches_visibility_filters?'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.29.0/lib/capybara/node/element.rb:300:in `visible?'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.29.0/lib/capybara/node/base.rb:77:in `synchronize'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.29.0/lib/capybara/node/element.rb:300:in `block in visible?'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.29.0/lib/capybara/selenium/nodes/edge_node.rb:67:in `visible?'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.29.0/lib/capybara/selenium/node.rb:150:in `visible?'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/element.rb:199:in `displayed?'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:509:in `element_displayed?'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/atoms.rb:13:in `execute_atom'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:292:in `execute_script'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:552:in `execute'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:91:in `create_response': **unexpected response, code=500, content-type="text/plain" (Selenium::WebDriver::Error::WebDriverError)
Unknown error**

## Steps to reproduce
Create a simple ruby file with Capybara and launch Edge browser and perform user actions like click and sendkeys.

I triggered the execution without capybara and the code was able to do the user action.
Let me know if there are any compatibility issues between the Capybara and Edge Browser.

**Below is the ruby code used to do the execution**

require 'selenium/webdriver'
require 'capybara/rspec'

include Capybara::DSL

Capybara.default_driver = :selenium
Capybara.register_driver :selenium do |app|
 #client = Selenium::WebDriver::Remote::Http::Default.new

options = Selenium::WebDriver::Edge::Options.new(in_private: true)
#driver = Selenium::WebDriver.for :edge, options: options
$driver=Capybara::Selenium::Driver.new(app, browser: :edge)
end
capabilities = Capybara.current_session.driver.browser.capabilities
puts "running the tests with capabilities #{capabilities.inspect}"

$driver.visit("https://www.**AAAAAAAAAAAAAAAAAAA**")
sleep 5
element=$driver.find(:xpath,"//button[@data-automation='header-search']")
element.click
sleep 3
$driver.find(:xpath,"//input[@data-automation='input-search']").send_keys "shaver"

**Comment by luke-hill** [comment] 2019-12-31 11:09
Your stacktrace mentions line 1 failing on an each function. In the code below you don't have this code called.

What happens when you run the small script below

**Comment by kishorekumartbm** [comment] 2019-12-31 11:22
Below is the snapshot of code and error 

![image](https://user-images.githubusercontent.com/59390185/71620033-a7d95a00-2c1b-11ea-9ab0-3f9b1ac96293.png)
![image](https://user-images.githubusercontent.com/59390185/71620087-f129a980-2c1b-11ea-9bcc-188433f4ff48.png)

**Comment by luke-hill** [comment] 2019-12-31 11:41
I've got almost identical code passing for me. If you can push the code up to a git repo that I can run it against then I might be able to find out what is going wrong.

From your code it looks like the first call to `$driver` visiting the website may be the problem but the stacktrace seems a bit odd. So if you push something up i'll pull it down and have a play

**Comment by kishorekumartbm** [comment] 2019-12-31 12:03
It is just a simple Ruby File. I already have the gems installed so it is not a complete project.
Attached both the  files for your reference

[selenium-edge-capy.zip](https://github.com/teamcapybara/capybara/files/4012632/selenium-edge-capy.zip)

**Comment by twalpole** [comment] 2019-12-31 17:39
Your question states Capybara 3.19 but the stacktrace shows 3.29 so I assume the question is a typo...   Is there a specific reason you're using selenium-webdriver 3.141.0  when there was a later 3.141.x release as well as a few 3.142.x releases?

From the stacktrace we can see the error is happening when selenium-webdriver is checking if the element is visible or not, by running some JS (the `execute_atom` call).  Capybara does provide replacement atoms to fix some issues in the selenium provided atoms, so it's possible the provided atoms aren't compatible with the old (non-chromium) Edge. You can check this by setting an environment variable named `DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS` to true. If doing that fixes the issue then  https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/atoms/src/isDisplayed.js will need to be looked at to determine what isn't supported by Edge.  I don't currently have access to a windows machine though so someone else will need to do that investigation.

**Comment by twalpole** [comment] 2019-12-31 17:46
On a side note - your example file uses XPath to match elements by the `data-automation` attribute (which I assume you're adding specifically for testing).  Two improvements you could do with that are

1.  You're starting you're XPaths with `//` which is almost never what you want - instead you should be starting with `.//` (see https://github.com/teamcapybara/capybara#beware-the-xpath--trap)
2.  You can set `Capybara.test_id = 'data-automation'` which will then make the Capybara provided selector types match on the `data-automation` attribute whenever it would also match an elements id.  This would allow you to do `click_button('header-search')` and `fill_in('input-search', with: 'shaver')` rather than using XPaths

**Comment by kishorekumartbm** [comment] 2020-01-01 04:23
> Your question states Capybara 3.19 but the stacktrace shows 3.29 so I assume the question is a typo... Is there a specific reason you're using selenium-webdriver 3.141.0 when there was a later 3.141.x release as well as a few 3.142.x releases?
> 
> From the stacktrace we can see the error is happening when selenium-webdriver is checking if the element is visible or not, by running some JS (the `execute_atom` call). Capybara does provide replacement atoms to fix some issues in the selenium provided atoms, so it's possible the replacement atoms aren't compatible with the old (non-chromium) Edge. You can check this by setting an environment variable named `DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS` to true, which will disable Capybara from using its replacement atoms. If doing that fixes the issue then https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selenium/atoms/src/isDisplayed.js will need to be looked at to determine what isn't supported by Edge. I don't currently have access to a windows machine though so someone else will need to do that investigation.


I tried with many versions of capybara(3.10,3.19,3.10) and we are using 3.19 version in our project.
But all the versions of capybara results the same error.

Do you have any example on how to set the 'DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS' to true?

Below error log is from 3.19
including Capybara::DSL in the global scope is not recommended!
running the tests with capabilities #<Selenium::WebDriver::Remote::W3C::Capabilities:0x000000000477c258 @capabilities={:proxy=>nil, :browser_name=>"MicrosoftEdge", :browser_version=>"44.17763.831.0", :platform_name=>"windows", :accept_insecure_certs=>false, :page_load_strategy=>"normal", :implicit_timeout=>0, :page_load_timeout=>300000, :script_timeout=>30000, :remote_session_id=>nil, :accessibility_checks=>nil, :profile=>nil, :rotatable=>nil, :device=>nil, "setWindowRect"=>false}>
Traceback (most recent call last):
        20: from ./selenium-edge-capy.rb:1:in `each'
        19: from ./selenium-edge-capy.rb:1:in `each'
        18: from ./selenium-edge-capy.rb:1:in `each'
        17: from ./selenium-edge-capy.rb:1:in `each'
        16: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.19.0/lib/capybara/result.rb:32:in `block in initialize'
        15: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.19.0/lib/capybara/queries/selector_query.rb:88:in `matches_filters?'
        14: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.19.0/lib/capybara/queries/selector_query.rb:389:in `matches_system_filters?'
        13: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.19.0/lib/capybara/queries/selector_query.rb:449:in `matches_visible_filter?'
        12: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.19.0/lib/capybara/node/element.rb:290:in `visible?'
        11: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.19.0/lib/capybara/node/base.rb:77:in `synchronize'
        10: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.19.0/lib/capybara/node/element.rb:290:in `block in visible?'
         9: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/capybara-3.19.0/lib/capybara/selenium/node.rb:144:in `visible?'
         8: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/common/element.rb:199:in `displayed?'
         7: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:509:in `element_displayed?'
         6: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/atoms.rb:13:in `execute_atom'
         5: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:292:in `execute_script'
         4: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/w3c/bridge.rb:552:in `execute'
         3: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/bridge.rb:166:in `execute'
         2: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:62:in `call'
         1: from C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/default.rb:104:in `request'
C:/Ruby25-x64/lib/ruby/gems/2.5.0/gems/selenium-webdriver-3.141.0/lib/selenium/webdriver/remote/http/common.rb:91:in `create_response': unexpected response, code=500, content-type="text/plain" (Selenium::WebDriver::Error::WebDriverError)
Unknown error

**Comment by kishorekumartbm** [comment] 2020-01-01 04:24
> I've got almost identical code passing for me. If you can push the code up to a git repo that I can run it against then I might be able to find out what is going wrong.
> 
> From your code it looks like the first call to `$driver` visiting the website may be the problem but the stacktrace seems a bit odd. So if you push something up i'll pull it down and have a play

Can you share your sample code and the capybara, selenium, ruby and edge versions? so that I will try  the same setup in my machine

**Comment by twalpole** [comment] 2020-01-02 18:05
@kishorekumartbm DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS needs to be an environment variable - set it however you set environment variables for a specific process (or global) on your platform - in mac/linux that could be something like

    DISABLE_CAPYBARA_SELENIUM_OPTIMIZATIONS=true ruby my_test_file.rb

In Windows it varies based on your version -- but google can be your friend

**Comment by twalpole** [comment] 2020-01-03 18:51
I've tried running the Capybara specs against Edge 18 (which I believe corresponds to the 44.17763.831.0 listed) using Browserstack and they find elements without issue, so without a way to actually replicate this there's not much more I can do.

**Comment by luke-hill** [comment] 2020-01-14 08:50
As an update @twalpole I also had no issue running against a remote instance and then hitting Edge and finding elements. I think either his machine has something set up weird or the page is weird. Because it's not a fully reproducible SSCCE

**Comment by twalpole** [comment] 2020-01-14 13:26
Closing as non-reproducible

**Closed by twalpole** 2020-01-14 13:26 UTC
Labels: Can’t Replicate
