### ISSUE TITLE
Feature tweak: `have_text/have_content` to be scoped to Capybara::Node::Element where appropriate

### ISSUE THREAD

**Issue by luke-hill** [teamcapybara/capybara#1970] opened 2018-02-16 09:33 UTC
This isn't technically a bug, but in someone trying to fix a bug on the Siteprism repo here: https://github.com/natritmeyer/site_prism/pull/174 it seems as though actually the reason for it failing is legit.

The code we're calling is here: https://github.com/teamcapybara/capybara/blob/master/lib/capybara/rspec/matchers.rb#L274-L279 Which states that `have_text` only works on a page.

However all the other matchers in the area seem to be scoped to element.

Is there a reason for this, do we have to fix this our end? (The way in which the PR attempts to do so is to override the value of page at a section level)

Cheers

Luke

**Comment by twalpole** [comment] 2018-02-16 17:55
They should be scoped to the current element. I've recently seen a similar comment about this issue in some other peoples code I was looking at and don't really see how it's possible for it to not be scoping, so if you can provide an example that reproduces it I'd love to see it

**Comment by twalpole** [comment] 2018-02-16 23:32
FYI -- you may want to look at, and comment on, PR #1974 - which may allow you to fix your issue (at the cost of going Capybara 3.0+) if I decide to include it.  Closing this for now since Capybaras have_text/have_content do work on the current element or scope (without proof to the contrary)

**Closed** 2018-02-16 23:32 UTC
