### ISSUE TITLE
Possible regression in has_text? between 2.18.0 and 3.0.0

### ISSUE THREAD

**Issue by jaredbeck** [teamcapybara/capybara#2001] opened 2018-04-06 18:36 UTC
## Meta
Capybara Version: 3.0.0
Driver Information (and browser if relevant): N/A

## Behavior in 2.18.0

2.18.0 normalizes whitespace, as documented above `def has_text?`

```
require 'capybara'
page = Capybara::Node::Simple.new("<p>foo\nbar</p>")
page.has_text?("foo bar")
#=> true
```

## Behavior in 3.0.0

Normalization of whitespace in 3.0.0 does not match documentation above `def has_text?`

```
require 'capybara'
page = Capybara::Node::Simple.new("<p>foo\nbar</p>")
page.has_text?("foo bar")
#=> false
```

## My question

Is this an intended breaking change in 3.0.0 (and the documentation above `def has_text?` needs to be updated) or is it a regression? I don't see a mention of it in the changelog.

**Comment by twalpole** [comment] 2018-04-06 18:49
It is a breaking change in 3.0.0 so the documentation probably needs to be fixed.  It is mentioned in the  changelog as "Drivers are now expected to return visible text more in line with the WebDriver spec for visible text"  which probably could have been clearer, but is intended to return text that is formatted more like the browser displays it.

**Comment by twalpole** [comment] 2018-04-06 19:01
Fixed via 0c2bf584ca0fcec5a412289b840388955e7fb2c6

**Closed by twalpole** 2018-04-06 19:01 UTC
Labels: Documentation

**Comment by jaredbeck** [comment] 2018-04-06 19:44
Thanks for the quick reply Thomas. I think this change should be highlighted in UPGRADING.md, and I will open a PR for that.

**Comment by jalada** [comment] 2018-05-02 09:50
I've got a test for a downloadable CSV, where the newline is actually being stripped _away_ with Capybara 3:

`
Failure/Error: expect(page).to have_content(User.csv_headers.to_csv)
  expected to find text "First name,Last name,Email,Telephone,Company,Admin account?,Trial account?,Confirmed?,Locked?,Account expiry,Latest sign in,Sign in count,Status,Created at,Confirmed at\n" in "First name,Last name,Email,Telephone,Company,Admin account?,Trial account?,Confirmed?,Locked?,Account expiry,Latest sign in,Sign in count,Status,Created at,Confirmed at Felisha,Mante,ashly@breitenberg.name,(795)950-5861 x434,Bernhard-Mills,false,true,true,false,2018-05-31,,0,Complete,2018-05-01 06:56:43 +0100,2018-05-01 06:56:43 +0100 Carmel,Hilpert,timothy@crona.co.uk,1-701-432-1106,Glover-Predovic,true,false,true,false,2018-05-31,2018-05-01 06:56:43 +0100,1,Complete,2018-05-01 06:56:43 +0100,2018-05-01 06:56:43 +0100"
`

(Data is from Faker)

But it sounds like if anything, the opposite should've been the case. Does anyone have any suggestions as to what's happening here?

**Comment by twalpole** [comment] 2018-05-02 10:01
@jalada What driver (and version) are you using?  Also what is the raw html?

**Comment by jalada** [comment] 2018-05-02 10:49
It's RackTest, Capybara 3.0.3. Running `page.html` shows the newline:

```
(byebug) page.text
"First name,Last name,Email,Telephone,Company,Admin account?,Trial account?,Confirmed?,Locked?,Account expiry,Latest sign in,Sign in count,Status,Created at,Confirmed at Edna,Gleichner,don.kassulke@rohan.com,361.428.8441,\"Borer, Mayert and Eichmann\",false,true,true,false,2018-06-01,,0,Complete,2018-05-02 11:47:01 +0100,2018-05-02 11:47:01 +0100 Nadine,Hegmann,lasonya@kshlerinfahey.com,1-731-717-6255 x0134,Effertz Group,true,false,true,false,2018-06-01,2018-05-02 11:47:02 +0100,1,Complete,2018-05-02 11:47:01 +0100,2018-05-02 11:47:01 +0100"
(byebug) page.html
"First name,Last name,Email,Telephone,Company,Admin account?,Trial account?,Confirmed?,Locked?,Account expiry,Latest sign in,Sign in count,Status,Created at,Confirmed at\nEdna,Gleichner,don.kassulke@rohan.com,361.428.8441,\"Borer, Mayert and Eichmann\",false,true,true,false,2018-06-01,,0,Complete,2018-05-02 11:47:01 +0100,2018-05-02 11:47:01 +0100\nNadine,Hegmann,lasonya@kshlerinfahey.com,1-731-717-6255 x0134,Effertz Group,true,false,true,false,2018-06-01,2018-05-02 11:47:02 +0100,1,Complete,2018-05-02 11:47:01 +0100,2018-05-02 11:47:01 +0100\n"
```
