### ISSUE TITLE
ArgumentError: wrong number of arguments (given 2, expected 0..1)

### ISSUE THREAD

**Issue by kyrofa** [teamcapybara/capybara#2666] opened 2023-05-08 22:16 UTC
selenium-webdriver v4.9.1, released [just hours ago](https://github.com/SeleniumHQ/selenium/releases/tag/selenium-4.9.1), breaks Capybara on Ruby 3.

It introduces a feature (in a patch :roll_eyes:) to specify the logging level when creating a logger, and [makes use of it](https://github.com/SeleniumHQ/selenium/blob/bc7e0c7341fdde78cdd80ce572002a7866fd1769/rb/lib/selenium/webdriver.rb#L99). That exposes [Ruby-2-era argument forwarding in Capybara](https://github.com/teamcapybara/capybara/blob/56a1bdfdb43fe4c06d0eea54018801c9d356cd1b/lib/capybara/selenium/logger_suppressor.rb#L6) that doesn't properly handle forwarding both positional and keyword arguments.

Take this simple example:

```ruby
class Foo
  def initialize(*args, **kwargs)
    puts "ARGS: #{args}, KWARGS: #{kwargs}"
  end
end

class Bar < Foo
  def initialize(*)
    super
  end
end

puts 'Foo:'
Foo.new('positional', keyword: 'argument')

puts 'Bar:'
Bar.new('positional', keyword: 'argument')
```

This runs fine on ruby 2.5:

```
$ rvm-exec 2.5.8 ruby example.rb
Foo:
ARGS: ["positional"], KWARGS: {:keyword=>"argument"}
Bar:
ARGS: ["positional"], KWARGS: {:keyword=>"argument"}
```

Also fine on 2.7:

```
$ rvm-exec 2.7.5 ruby example.rb
Foo:
ARGS: ["positional"], KWARGS: {:keyword=>"argument"}
Bar:
ARGS: ["positional"], KWARGS: {:keyword=>"argument"}
```

However, it does NOT work on 3.0:

```
$ rvm-exec 3.0.4 ruby example.rb
Foo:
ARGS: ["positional"], KWARGS: {:keyword=>"argument"}
Bar:
ARGS: ["positional", {:keyword=>"argument"}], KWARGS: {}
```

**Comment by aramprice** [comment] 2023-05-08 22:52
See also
- https://github.com/teamcapybara/capybara/pull/2665

**Comment by clairity** [comment] 2023-05-09 15:31
I ran into this error yesterday as well (ruby 3.2.2/rails 7.1.alpha) and added `Selenium::WebDriver.logger.output = 'log/selenium.log'` to `ApplicationSystemTestCase` in `test/system/application_system_test_case.rb` , which seemed to suppress the error and generates the denoted log file in the `log` directory.

i'm a novice in this domain so i'll defer to others here for the best solution, but perhaps it's better to have such log files, and to add generalized instructions to the documentation if folks run into this error?

**Comment by jrochkind** [comment] 2023-05-09 16:03
I can confirm that setting `Selenium::WebDriver.logger.output` _does_ seem to be a workaround for me -- I couldn't possibly explain why -- but surely it is not in fact better to require and document that you turn on selenium logging!  The underlying bug should be fixed.

**Comment by jrochkind** [comment] 2023-05-09 16:07
I can confirm that setting `Selenium::WebDriver.logger.output` _does_ seem to be a workaround for me.

`Selenium::WebDriver.logger.output = false` also works. 

Surely the underlying bug should be fixed rather than documenting the workaround though. 

Thanks @kyrofa for the great diagnosis. 

As a temporary workaround, I'm interested in what `Selenium::WebDriver.logger.output` line would correspond to default...

**Comment by jrochkind** [comment] 2023-05-09 16:27
OK, actually as a (temporary!) workaround, it seems to work to simply reference:

`Selenium::WebDriver.logger` in code before a call to capybara `visit`.   

No need to configure it or assign anything to it, just putting `Selenium::WebDriver.logger` in your initialization code somewhere seems to work as a workaround. 

I guess it lazily initializes the logger through a different code path than the one that was triggering the capybara bug? I can't explain the details. 

Thanks @clairity for the hint that doing something with `Selenium::WebDriver.logger`  could comprise a workaround. 

I still eagerly await a capybara release that fixes the underlying problem!

**Comment by BrianHawley** [comment] 2023-05-09 17:26
In lib/capybara/selenium/logger_suppressor.rb change the `initialize` method to this:
```ruby
def initialize(...)
  @suppress_for_capybara = false
  super
end
```
The `...` makes it also forward keyword arguments.

**Comment by twalpole** [comment] 2023-05-10 04:43
The real problem here is a breaking change in a patch release of selenium -- not sure how that got approved... will need to check on that

**Closed** 2023-05-10 05:05 UTC

**Comment by jrochkind** [comment] 2023-05-10 11:57
@twalpole if i understand @kyrofa's diagnosis, the change in selenium behavior triggers an already-existing capybara bug (method delegation in a way that stops working the same in ruby 3, and starts failing for methods with keyword args), that just hadn't been triggered (at least in default paths) before.  

Whether or not _without_ that bug the selenium change would be considered a breaking change... I guess is for others to discuss with selenium maintainers! 

Either way, thank you for merging #2667 which should resolve this from capybara's end!  It would be super helpful to see a capybara release, since many people are going to run into this problem with current selenium and capybara latest releases.

**Comment by kyrofa** [comment] 2023-05-10 15:40
Yeah I think from selenium's perspective this was a backward-compatible change. I think they should have bumped the minor version and not the patch, but that semantics (pun intended).

**Comment by kennyadsl** [comment] 2023-05-11 09:17
Hello! Thanks for the fix on this! This issue is also hitting us on @solidusio, and it would be great to have a new capybara version released with this fix, besides what other gems like `selenium-webdriver` do.

**Comment by clairity** [comment] 2023-05-12 18:48
i can confirm i no longer need [my workaround](https://github.com/teamcapybara/capybara/issues/2666#issuecomment-1540401523) (setting `Selenium::WebDriver.logger.output`) with the fix provided by #2667.

**Comment by twalpole** [comment] 2023-05-12 22:50
@clairity 3.39.1 was released a couple of hours before you posted -- please update

**Comment by kyrofa** [comment] 2023-05-12 22:55
Thanks @twalpole!

**Comment by waiting-for-dev** [comment] 2023-05-13 03:29
Thanks, @twalpole!
