### ISSUE TITLE
Net::ReadTimeout (Net::ReadTimeout) on driver.reset! with selenium_webdriver Chrome headless

### ISSUE THREAD

**Issue by seanrobbins** [teamcapybara/capybara#2193] opened 2019-05-21 14:08 UTC
## Meta
Capybara Version: 3.2.1
Driver Information (and browser if relevant):
selenium-webdriver 3.141.0 with Chrome 74.0.3729.157
Used with cucumber/rails
On MacOS Mojave

## Expected Behavior

Capybara.reset_session! call in After step completes successfully

## Actual Behavior

Capybara.reset_session! times out. Isolated this to the driver.reset! (can replicate by calling Capybara.current_session.driver.reset! directly)

      Net::ReadTimeout (Net::ReadTimeout)
      ./features/support/env.rb:128:in `After'
      Net::ReadTimeout (Net::ReadTimeout)

## Steps to reproduce

1. Launch chromedriver Headless in Capybara. Our code for this looks like this:

```
browser_options = ::Selenium::WebDriver::Chrome::Options.new
browser_options.headless! unless ENV['debug']

Capybara.register_driver :selenium_chrome do |app|
  Capybara::Selenium::Driver.new(app, browser: :chrome, options: browser_options)
end
```

2. Visit at least one page

3. Call Capybara.current_session.reset_session!

## Additional Info

Working around by locking bundle down to using 3.12.0 (last known good version with out set up).

Issue does not occur when running Chrome non-headless. Can only reproduce when Chrome is being run Headlessly.

**Comment by twalpole** [comment] 2019-05-21 15:51
Capybara 3.2.1 is not current, so I assume that's a typo and you mean 3.20.1?  Assuming it is, I believe this a duplicate of #2181

**Closed by twalpole** 2019-05-21 15:51 UTC
