### ISSUE TITLE
As of Puma 6.0.0, Puma::Event has no `strings` method, breaking `Capybara.register_server :puma`

### ISSUE THREAD

**Issue by patrick-laa** [teamcapybara/capybara#2595] opened 2022-10-17 14:38 UTC
## Meta
Capybara Version: 3.37.1

## Actual Behavior

```
terminated with exception (report_on_exception is true):
[...]/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/registrations/servers.rb:32:in `block in <top (required)>': undefined method `strings' for Puma::Events:Class (NoMethodError)

  events = conf.options[:Silent] ? ::Puma::Events.strings : ::Puma::Events.stdio
                                                 ^^^^^^^^
	from [...]/vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/config.rb:64:in `block in server='
	from .../vendor/bundle/ruby/3.1.0/gems/capybara-3.37.1/lib/capybara/server.rb:77:in `block in boot'
```

## Steps to reproduce
Use Capybara 3.37.1 with Puma 6.0.0

**Comment by twalpole** [comment] 2022-10-17 22:46
Duplicate of https://github.com/teamcapybara/capybara/issues/2594

**Closed** 2022-10-17 22:47 UTC
