### ISSUE TITLE
Interactions with modals stopped working with chrome 73

### ISSUE THREAD

**Issue by lcx** [teamcapybara/capybara#2171] opened 2019-03-26 15:35 UTC
## Meta
Capybara Version:
3.15

Driver Information (and browser if relevant):

headless chrome=73.0.3683.86
Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.13.6 x86_64

## Expected Behavior

Fields should be filled in and modal closed after button is clicked.

## Actual Behavior

```
     Selenium::WebDriver::Error::UnknownError:
       unknown error: Element <a class="btn btn-primary new-contact-r" href="#" data-target=".contact-modal" data-toggle="modal" id="new-contact">...</a> is not clickable at point (379, 376). Other element would receive the click: <input type="text" name="contact[email]" id="contact_email" value="" class="form-control">
         (Session info: headless chrome=73.0.3683.86)
         (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Mac OS X 10.13.6 x86_64)
```

## Steps to reproduce

After a chrome update to 73.0.3683.86 some specs started failing, ones that included modals. I upgraded slenium-webdriver & capybara but specs still fail with above message. 
If I add a `save_and_open_screenshot` right before the failing click then specs would pass, same happens if I add a `sleep 1` or `binding.pry`. 
I replaced chrome_headless with selenium_chrome to see what's happening, the text fields seem like they are filled for a fraction of a second and then the text disappears from the text field. 
For example this piece of spec here: 

```
      click_on 'new-contact'
      fill_in 'contact_first_name', with: 'James'
      expect(page).to have_content(I18n.t('labels.personal_details'))
      click_on 'save-contact-modal'
```

`click_on 'new-contact` opens the modal, name is filled and remains filled only with the expect(page) line in there (or screenshot, binding.pry, sleep)
I'm not sure if this is a capybara issue or something else, after all it seemed to have happened after the chrome update. 
Downgrading to chrome 72 and passing a binary to chromeOptions to use the older version solves this issue. 

:headless_chrome is defined like this

```
Capybara.register_driver(:headless_chrome) do |app|
  capabilities = Selenium::WebDriver::Remote::Capabilities.chrome(
    chromeOptions: {
      args: %w[headless disable-gpu no-sandbox disable-dev-shm-usage window-size=1536,752]
    }
  )

  Capybara::Selenium::Driver.new(
    app,
    browser: :chrome,
    desired_capabilities: capabilities
  )
end
```

**Comment by twalpole** [comment] 2019-03-26 21:46
I'm assuming by "modals" you mean a modal window implemented by some JS framework as opposed to system modals (accept/prompt/confirm).  Since dropping back to Chrome 72 works it would tend to imply changed behavior in either Chrome 73 or chromedriver 73, but without a concise reproducible way to replicate this there's not much I can do to try and figure out what has changed.  

That being said the error is pretty explanatory as to the issue.  The input element is overlapping the link element you're trying to click.  There are many reasons why this could be happening, but the two most common are your window not being big enough to correctly display whats on the screen or that what's on the screen is animating into view and you haven't disabled those animations in the test environment or set an expectation to check for the container having finished its animation

**Comment by lcx** [comment] 2019-03-27 07:27
Yes indeed it was a Bootstrap Modal, sorry forgot to mention that.
I have no animations and everything that is happening is just filling a form field with fill_in. The sleep fix only works if I add it after the fill_in it does not work if I add it after clicking to open the modal.
I will have to play around with it a bit more and probably also test on a clean project to see if I can reproduce it in any other way. 
The fill_in is being using with other specs where there is no bootstrap modal, there I have no issue. 
Looking at the screenshot I get when the spec fails is inline with the error message since the modal is still open.

**Comment by twalpole** [comment] 2019-03-27 16:49
A Bootstrap modal uses animation by default to appear, so even though you may not have added extra animations, it doesn't mean none are being used.  Also, I may have misread the issue first time - which line is the error coming from? I initially assumed the `click_on 'save-contact-modal'` line - but rereading the selectors in the error message it looks like it may be from the `click_on 'new-contact'` line, but then that doesn't align with having a sleep after that fixing the issue - so I'm confused.  Obviously a reproducible example would make this much easier to diagnose.

**Comment by twalpole** [comment] 2019-03-30 16:14
Were you able to determine any more info here or reproduce this in a minimal self contained example?

**Comment by twalpole** [comment] 2019-04-03 20:08
Closing this until more info/reproducible example is provided - will reopen if/when that is provided

**Closed by twalpole** 2019-04-03 20:08 UTC
Labels: Waiting for response
