### ISSUE TITLE
undefined method `current_scope' for Obsolete #<Capybara::Node::Element>:Capybara::Node::Element

### ISSUE THREAD

**Issue by GalenkoEugene** [teamcapybara/capybara#2341] opened 2020-04-28 07:52 UTC
## Meta
Capybara Version:
3.31.0 (_and higher_)
Driver Information (and browser if relevant):
selenium-webdriver (3.142.7) with Chrome 81.0.4044.122
site_prism (3.4.2)

## Expected Behavior
Shouldn't raise an error

## Actual Behavior
undefined method `current_scope' for Obsolete #<Capybara::Node::Element>:Capybara::Node::Element

## Steps to reproduce
```ruby
expect(page.month_section).to have_css('.month-picker__box.disabled')
```

**Comment by twalpole** [comment] 2020-04-28 15:38
The step to reproduce is missing a lot of context that would actually be necessary to reproduce this.  If you can provide a self contained example that reproduces the error I will look into this, otherwise I will close this issue in a couple of days.  I will point out that `current_scope` is a session method and it looks like in your code it's being called on an `Element` which is wrong.  My gut instinct would be a site_prism bug.

**Comment by twalpole** [comment] 2020-04-29 22:27
I'm going to close this.  If a self contained example is provided that shows the issue and it is a Capybara issue I'll reopen

**Closed by twalpole** 2020-04-29 22:27 UTC
