### ISSUE TITLE
have_no_select with with_options: behaves unexpectedly

### ISSUE THREAD

**Issue by zimski** [teamcapybara/capybara#2118] opened 2018-10-26 14:56 UTC
Hello,

I have an issue with this `have_no_select` used `with_options:` that match a part of the `option` instead of matching the whole of it.
This is valid too  for the `have_select` too

## Steps to reproduce
```html
    <label for="form_hour">Hour</label>
    <select name="form[hour]" id="form_hour">
      <option>3h00</option>
      <option>22h00</option>
      <option>12h00</option>
    </select>

```

The expectation

```ruby
    expect(@session).to have_no_select('Hour', with_options: ['2h00'])
```
## Expected Behavior
success

## Actual Behavior
fail

## The explanation
When I dig in the code, the part responsible is the `xpath selector` used in this assertion : 

```
.//option[contains(normalize-space(string(.)), '2h00')
```
And this query will return the node because we have a **partial match** with `22h00` and `12h00`

I will be happy to help If I get some hints to make the best fix for this

Thank you

**Comment by twalpole** [comment] 2018-10-26 17:16
This behavior is as expected since the :option selector type -https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector.rb#L347 - which is used for `with_options` - https://github.com/teamcapybara/capybara/blob/master/lib/capybara/selector.rb#L281 - defaults to substring matching (via the default setting of Capybara.exact = false affecting how the XPath library `is` method is interpreted ) and is how `#select` works too.  If you want exact matching for the `have_no_select` matcher you can specify the exact option

    expect(@session).to have_no_select('Hour', with_options: ['2h00'], exact: true)

Note: the exact there would also affect the 'Hour' locator for the select, so depending on exactly what you want you may want to rewrite that as

    expect(@session.find(:select, 'Hour')).not_to have_selector(:option, '2h00', exact: true)

which would verify that there is an 'Hour' select but that it doesn't have '2h00' as an option, whereas your previous expectation would succeed if there was no 'Hour' select at all.  

I'm willing to keep discussing this if you'd like but for now I'm going to close this issue since it's as designed.  If you think a documentation update would make this clearer I'm more than willing to accept a PR

**Closed by twalpole** 2018-10-26 17:16 UTC
