### ISSUE TITLE
A race condition in `#reset_browser_state`

### ISSUE THREAD

**Issue by sidonath** [teamcapybara/capybara#2211] opened 2019-05-27 16:21 UTC
Hi there! 👋

I discovered a funky race-condition that was causing a flakiness in our Rails system tests for a long time. We have a work-around in our app (removing all cookies in `teardown` blocks), but I was wondering if the problem could/should be fixed within Capybara.

(This is potentially a duplicate of #738, but as that issue is very old and lacks a lot of context, I decided to start a new one).

## Meta

Capybara Version: 3.20.2
Driver Information (and browser if relevant): selenium-webdriver (3.142.2) with Headless Chrome 74

## Expected Behavior

All cookies (and state in general) are being reset between tests.

## Actual Behavior

When using Selenium, sometimes, a user session cookie doesn't get deleted after a system test, thus potentially failing a following system test in our app.

I dug down and figured out that this behavior could be explained by a race condition in `Capybara::Selenium::Driver#reset_browser_state`: if an ajax request that contains `Set-Cookie` header ends after cookies have been cleared by `#clear_browser_state`, the ajax request will set a new cookie and only then the browser will navigate to `about:blank` (which cancels all requests in progress).

I tried reordering the statements: to first navigate to `about:blank` and then clear the browser state, but that results in the following Capybara's specs failing:

```
  1) Capybara::Selenium::Driver storage #reset! clears storage by default
     Failure/Error: expect(session.driver.browser.local_storage.keys).to be_empty
       expected `["local"].empty?` to return true, got false
     # ./spec/selenium_spec_firefox.rb:162:in `block (4 levels) in <top (required)>'

  2) Capybara::Session selenium #reset_session! removes cookies from current domain
     Failure/Error: expect(@session.body).not_to include('test_cookie')
       expected "<html><head></head><body>test_cookie</body></html>" not to include "test_cookie"
     # ./lib/capybara/spec/session/reset_session_spec.rb:11:in `block (2 levels) in <top (required)>'
```

I also tried the following:

```ruby
def reset_browser_state
  clear_browser_state
  @browser.navigate.to('about:blank')
  clear_browser_state
end
```

And it fixes the issue when using Chrome, but not when using Firefox.

I guess we would need to somehow cancel all requests before clearing the state to ensure new state—such as cookies—wouldn't be set.

I figured navigating to `about:blank` effectively cancels all in-progress ajax requests, but the following causes many more Capybara tests to fail:

```ruby
def reset_browser_state
  previous_path = current_url
  # Cancel all in-progress ajax requests by navigating away
  @browser.navigate.to('about:blank')
  # Go back to the domain that has state and clear it
  @browser.navigate.to(previous_path)
  clear_browser_state
  # Now we can navigate away
  @browser.navigate.to('about:blank')
end
```

Any other ways to fix this issue? 😊 

## Steps to reproduce

There's no out-of-the box way to consistently reproduce this issue, but I amended `#reset_browser_state` with `sleep` which makes it possible to write a spec. Please see this commit in my fork: https://github.com/sidonath/capybara/commit/ad2effc68ee1d56f6d30846b030b2b4923d50c43

**Comment by twalpole** [comment] 2019-05-27 18:15
The root cause here is that the webdriver spec only allows for clearing cookies (and since local/session storage are cleared via JS the same applies for them) that are valid for the current url so we can't go to `about:blank` and then clear the cookies (with webdriver compliant browser drivers).  One way of handling this is to have a specific path handled by the middleware (assuming Capybara is managing the AUT) that effectively becomes a "blank" page on the apps domain, but the overhead of doing that isn't worth it for the 99% of cases that don't need it.  The simplest solution if you have tests that are failing because of this is to add an after block, to the tests that need it, that navigates to a simple page in your app (that doesn't generate extra xhr requests) and then expects for something on that page.

**Comment by sidonath** [comment] 2019-05-27 18:36
@twalpole thanks for the response!

> The simplest solution if you have tests that are failing because of this is to add an after block, to the tests that need it, that navigates to a simple page in your app (that doesn't generate extra xhr requests) and then expects for something on that page. That way you end up on the correct domain with no chance of extra xhr requests occurring.

Makes sense. What about cancelling the ajax requests in progress? I guess this is a feature that we would need to get added to the WebDriver spec first.

I was really hoping we could do something general to prevent others running into the same issue again. Maybe at least add a note to README? 🤔 

> Note: your sleep solution only really solves the issue if you can be confident all requests will be finished in the time you're sleeping and no other requests will be initiated during that time - so it's not a general purpose solution.

Ah, `sleep` was never a solution, it was just there to make sure the test consistently fails. I couldn't figure out a better way to write a failing test for this issue.

**Comment by twalpole** [comment] 2019-05-27 18:43
How would you suggest we cancel the ajax requests?  Even with straight JS in the browser there is no generic way to get access to all current requests in order to cancel them. Then there's the issue of preventing new ones from being initiated at any given moment in time.  I'm open to adding a note to the READMEs gotchas section if you want to file a PR however it's not really a simple problem to summarize.

**Comment by twalpole** [comment] 2019-05-27 18:49
The easier thing to get into the WebDriver spec would probably be to allow clearing all cookies (and local/session storage) no matter what domain the browser is on (as Chrome does currently allow)

**Comment by twalpole** [comment] 2019-05-27 19:04
I forgot to mention - there is another solution which is to quit/restart the session after each test- but that also adds an unacceptable amount of overhead to the normal case.

**Comment by twalpole** [comment] 2019-05-27 19:43
@sidonath If you use Chrome for your tests you can try the chrome_reset branch fo this repo to see if your failures go away.  It changes the order of cookie clearing (since as I mentioned above Chrome/chromedriver does allow us to delete ALL cookies).  Wouldn't affect local or session storage though.

**Comment by sidonath** [comment] 2019-05-28 12:17
@twalpole thanks, Thomas! The change on the `chrome_reset` branch indeed prevents the failures for me.

> The easier thing to get into the WebDriver spec would probably be to allow clearing all cookies (and local/session storage) no matter what domain the browser is on (as Chrome does currently allow)

Makes sense, I can write an issue on w3c/webdriver.

**Comment by twalpole** [comment] 2019-05-28 22:06
Closing this for Chrome via 9db4cbf9ea87b6f5befc87e2d5d2d2add29b925f using the CDP functionality on 73+ - There is nothing we can do for other browsers.

**Closed by twalpole** 2019-05-28 22:06 UTC

**Comment by sidonath** [comment] 2019-05-29 10:28
@twalpole thanks! 🙇
