### ISSUE TITLE
Chrome crashes when changing domain name

### ISSUE THREAD

**Issue by n-rodriguez** [teamcapybara/capybara#2096] opened 2018-09-08 09:00 UTC
## Meta -
OS: Debian 9.5 Stretch
Selenium Version: selenium-webdriver-3.14.0
Browser: Chromium
Browser Version: 69.0.3497.81-1~deb9u1

## Expected Behavior -

No crash

## Actual Behavior -

```sh
Selenium::WebDriver::Error::WebDriverError:
 chrome not reachable
   (Session info: headless chrome=69.0.3497.81)
   (Driver info: chromedriver=2.41.578700 (2f1ed5f9343c13f73144538f15c00b370eda6706),platform=Linux 4.9.0-8-amd64 x86_64)
# /cache/nicolas/concerto/wip-test-french-site/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/response.rb:69:in `assert_ok'
# /cache/nicolas/concerto/wip-test-french-site/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/response.rb:32:in `initialize'
# /cache/nicolas/concerto/wip-test-french-site/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:84:in `new'
# /cache/nicolas/concerto/wip-test-french-site/ruby/2.5.0/gems/selenium-webdriver-3.14.0/lib/selenium/webdriver/remote/http/common.rb:84:in `create_response'
```

## Steps to reproduce -

Change domain name during tests.

**Comment by n-rodriguez** [comment] 2018-09-08 09:10
I've opened an issue on Selenium repo too : https://github.com/SeleniumHQ/selenium/issues/6381

**Comment by twalpole** [comment] 2018-09-08 09:18
What do you mean by “change domain name”, please show some code. Also you state that you’re using Chrome 69 but the error clearly shows 68 - please confirm what you’re actually using.

**Comment by n-rodriguez** [comment] 2018-09-08 09:25
I think the crash happens when Capybara hits the french website part.

The crash didn't happen before because I've just added tests on the french part.

**Comment by n-rodriguez** [comment] 2018-09-08 09:33
The `set_host` method : 

```ruby
  def set_host(host)
    Capybara.app_host = "http://#{host}:#{Capybara.server_port}"
  end
```

**Comment by n-rodriguez** [comment] 2018-09-08 09:35
The weird thing is that this issue only happens in CI, it works well on my laptop.

Ci config :
* Debian 9.5 Stretch
* Chromium 69.0.3497.81-1~deb9u1

Local config :
* ArchLinux
* Chromium 69.0.3497.81

**Comment by n-rodriguez** [comment] 2018-09-08 09:47
Actually I don't know if it's Capybara or Selenium or Chrome fault. That's why I've opened this 3 issues :

* https://github.com/SeleniumHQ/selenium/issues/6381
* https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=908142

**Comment by twalpole** [comment] 2018-09-08 17:48
Without a full stack trace I can't tell whether this is even occurring inside Capybara or not.  From the error it looks like either Chrome or chromedriver are crashing which wouldn't be a Capybara issue, but I have many test suites that use multiple domains and work just fine with Chrome/chromedriver.  Closing this until more info that shows it's a Capybara issue, or a way to reproduce is provided.

**Closed by twalpole** 2018-09-08 17:48 UTC
