### ISSUE TITLE
Feature request: allow finding by value of aria-labelledby

### ISSUE THREAD

**Issue by jcoyne** [teamcapybara/capybara#2429] opened 2020-12-04 22:28 UTC
Some elements point at another element that labels them using the `aria-labelledby` property. https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-labelledby_attribute

It would be great if Capybara could use this to find elements.

**Comment by matt17r** [comment] 2021-01-04 00:42
https://github.com/teamcapybara/capybara/pull/1732 suggests this can be achieved using XPath: `XPath.attr(:'aria-labelledby').equals(XPath.anywhere()[XPath.string.n.is(locator)].attr(:id))`

Is this still possible 4 years later or have things changed? If it's still possible, does this help in your use case @jcoyne?

**Comment by jcoyne** [comment] 2021-01-04 15:35
Yes, that would find it, but I was hoping this would be incorporated such that I could write `find_button('Whatever')` rather than an xpath expression.

**Comment by twalpole** [comment] 2021-01-21 18:24
PR would be accepted if it came with tests.  If a PR with just tests for expected behavior were submitted I will try and find time to update the xpaths, although I'm guessing it will be a pretty big performance hit to element finding if/when enabled.

**Comment by luke-hill** [comment] 2021-01-26 17:37
Does the [capybara_accessible_selectors](https://github.com/citizensadvice/capybara_accessible_selectors) gem help you at all?

**Comment by jcoyne** [comment] 2021-01-26 20:11
@luke-hill I didn't see anything in the documentation for capybara_accessible_selectors that says it supports `aria-labelledby` (I also did a cursory search of the code and found nothing).

**Comment by luke-hill** [comment] 2021-01-27 09:51
Oki. I know for instance we do support quite a few of the aria elements there. I'll ask at work today, it sounds like something that should be possible, but I've not switched to start using it yet.

**Comment by mrdaniellewis** [comment] 2021-01-27 18:20
The capybara_accessible_selectors only supports `aria-labelledby` for a couple of selectors where there is no native label (rich text and modal), and in a simplistic way as a `locator_filter`.

In general, I'd like to be able to find elements by their computed aria role and computed accessible name (ie the name a screen-reader gets).  There is no browser API to do that, though.  The [accessible naming algorithm](https://www.w3.org/TR/accname-1.1/) is quite complicated if all the edge cases are considered.  It would be impossible to implement as a xpath expression alone.

Maybe new role based selectors, with a `locator_filter` could do it: `find :textbox, "My accessible label"`.

Or maybe an `accessible_name` `node_filter` could be added: `find :field, accessible_name: "My accessible name"`

Or a combination of the two: `find :role, :textbox, name: "My accessible label"`.

Ideally any error message should also be able to list what roles and/or accessible names are available on the page.

**Comment by twalpole** [comment] 2021-08-30 15:40
Closing this since adding new aria functionality to Capybara just ends up creating selectors that are so complex and slow (due to the aria spec being so unconstrained) as to be useless in most circumstances.   IMO this functionality should be implemented in a separate gem if wanted.

**Closed by twalpole** 2021-08-30 15:40 UTC
