### ISSUE TITLE
Capybara/Cucumber tests time time out retrieving pages, despite having retrieved them

### ISSUE THREAD

**Issue by typhoon2099** [teamcapybara/capybara#2319] opened 2020-02-26 14:20 UTC
## Meta
Capybara Version:
3.31.0
Driver Information (and browser if relevant):
selenium-webdriver 3.142.7 with Chrome 72.0.3626.121
cucumber 3.1.2
cucumber-rails 2.0.0

## Expected Behavior
The Cucumber test finishes

## Actual Behavior
The test fails with `Requests did not finish in 60 seconds: ["/login"] (RuntimeError)`

## Steps to reproduce
Create a Rails app, add a file to the `public` directory called `login`, create a Cucumber Scenario that loads the login page, obeserve that the test found text on the page, but still timed out anyway.

**Comment by twalpole** [comment] 2020-02-26 15:40
When Capybara resets the page it tells the browser to go to `about:blank` and then waits for all the currently open requests to finish.  In your case the request that has been made to `/login` has not completed within 60 seconds.  Why it hasn't completed I have no idea, but it could be to do with Rails asset compilation.  If you want someone to look at this please provide a link to public example project that shows the behavior, but it's highly doubtful this is caused by Capybara.

**Comment by typhoon2099** [comment] 2020-02-26 16:42
The reason I raised this is because I've tested using a single my legs static file. There's no asset compilation I'm Rails, and the test loads the page, and conforms the text inside it, and then fails due to a timeout. I'm not sure what else could be causing the error if the page is loaded successfully and the tests pass.

**Comment by twalpole** [comment] 2020-02-27 05:28
Then create a public project on GitHub that shows the behavior and share a link to it

**Comment by twalpole** [comment] 2020-03-02 18:05
Closing this until a replication case is provided.  If/when a project replicating this is provided we will reopen.

**Closed by twalpole** 2020-03-02 18:05 UTC
