### ISSUE TITLE
fill_in sometimes appends to an input rather than overwriting

### ISSUE THREAD

**Issue by swrobel** [teamcapybara/capybara#2419] opened 2020-10-31 01:15 UTC
## Meta
* Capybara 3.33.0
* selenium-webdriver 3.142.7
* webdrivers chromedriver 86.0.4240.22
* Chrome Mac 86.0.4240.111

My code is very simple, and is accessing a user edit page with no special js (other than turbolinks). I've simplified slightly to get rid of the `faker` names so that it's obvious what's wrong in the screenshot:

```ruby
let(:user) { User.create(email: Faker::Internet.safe_email, name: "Old Name") }
let(:new_name) { "New Name" }
let(:new_email) { Faker::Internet.safe_email }

it "updates name, email" do
  visit url
  # take_screenshot <- adding this line fixes it, though using sleep instead does not
  fill_in "user[name]", with: new_name
  fill_in "user[email]", with: new_email
  expect {
    click "Save"
  }.to change { user.reload.name }.to(new_name) &
    change { user.email }.to(new_email)
end
```

However, I get:

```
expected `user.reload.name` to have changed to "New Name", but is now "Old NameNew Name"
```

If I add `take_screenshot` right before `expect`, you can see the strange behavior. Both `name` & `email` had previous values, but name gets appended to, and email gets overwritten.

![capybara](https://user-images.githubusercontent.com/157270/97767485-8f56fc00-1ad9-11eb-9ac2-51544ff72974.png)

## Expected Behavior
`fill_in "field", with: "string"` _overwrites_ existing "field" value with "string"

## Actual Behavior
`fill_in "field", with: "string"` _appends_ "string" to existing "field" value

## Steps to reproduce
This only seems to happen with the first filled field after visiting a page. Oddly, adding `sleep 1` before the first `fill_in` doesn't fix it, but using Rails system test's `take_screenshot` does. Another odd note is that this doesn't occur on my CircleCI (Linux) runs with the exact same Chrome/ChromeDriver versions - but it does occur on both of my Macs. Truly puzzling...

**Comment by twalpole** [comment] 2020-10-31 01:48
Without a way to reproduce there’s really not much we can do. Are you 100%sure there’s no JS being run on the page (it’s not a react page, etc)?  It sounds like the first click on an element is triggering some sort of page initialization JS

**Comment by swrobel** [comment] 2020-10-31 02:17
Yeah, I figured as much, and since it passes on CI I'm not terribly worried about it. Just figured out I'd document it here in case someone else has the same issue.

FYI, I removed all of my js includes from my application template and I still get the same behavior. No turbolinks - just pure rails templates!

**Comment by twalpole** [comment] 2020-10-31 22:17
It’s also possible this is a chromedriver bug - we have some intermittent failures on the emoji fill in test in capybaras test suite  where it sometimes appends

**Comment by mockdeep** [comment] 2020-11-21 02:58
FWIW, we found Chromedriver to be super flaky. Even with things as simple as clicking a link on a static html page, no JS, sometimes it would fail. Switching to Firefox caused pretty much all of the weird issues in our system tests to go away.

**Comment by nof** [comment] 2020-11-24 05:28
I have the same problem.
I had no choice but to put an empty fill_in before the original fill_in to get around it.

```
fill_in "user[name]", with: ''
fill_in "user[name]", with: new_name
```

**Comment by gstokkink** [comment] 2020-12-04 13:59
Same problem here with our test suite.

I fixed it as follows:

```
  Capybara.configure do |config|
    config.default_set_options = { clear: :backspace }
  end
```

This ensures the field is first cleared before the new value is set.

**Comment by alan-pie** [comment] 2021-01-04 21:15
Here is a chromium bug related to this issue that's been closed as "Won't Fix" because they need repro steps if someone here can produce them:
https://bugs.chromium.org/p/chromedriver/issues/detail?id=2842&q=appends&can=1

**Comment by Pezmc** [comment] 2021-03-16 09:59
We've also been hit by this exact problem, but only _sometimes_ across our test suite on OS X.
Run to run, different tests fail with the same append instead of replace issue.

```
Capybara 3.33.0
selenium-webdriver 3.142.7
webdrivers chromedriver 90.0.4430.24
Chrome Mac 90.0.4430.19

```

**Comment by twalpole** [comment] 2021-05-02 16:58
This is a chrome/chromedriver issue, possibly combined with timing on the framework (react/angular) the page is using, and not a Capybara issue.  If someone can provide a reproducible test to the chromedriver team they should investigate.

**Closed by twalpole** 2021-05-02 16:58 UTC

**Comment by alan-pie** [comment] 2021-05-04 15:21
I'm trying to figure out what Capybara calls in Selenium/Chromedriver so I might create a reproduction case. 
I got to [set_text](https://github.com/teamcapybara/capybara/blob/f7ab0b5cd5da86185816c2d5c30d58145fe654ed/lib/capybara/selenium/nodes/chrome_node.rb#L10) which seems to already mention a workaround for react for clearing.

Here is the Caopybara::Selenium::Node implementation of [set_text](https://github.com/teamcapybara/capybara/blob/f7ab0b5cd5da86185816c2d5c30d58145fe654ed/lib/capybara/selenium/node.rb#L270) which calls out to `native.send_keys`. I'm not sure of the type of `native` yet and need to dig a bit deeper.

**Comment by twalpole** [comment] 2021-05-04 16:29
@alan-pie `native` should be an instance of `::Selenium::WebDriver::Element` and https://github.com/teamcapybara/capybara/blob/f7ab0b5cd5da86185816c2d5c30d58145fe654ed/lib/capybara/selenium/node.rb#L281 is the default section of `set_text`

**Comment by softwaregravy** [comment] 2022-07-03 13:10
I am also seeing this in my project. I'll see if it's possible to carve off a piece of the project to be reproducible. I just wanted to add that we are running on straight Rails 7 with no React or JS.

**Comment by jamgregory** [comment] 2023-01-24 11:19
> Is anyone else seeing `Node#set but the RackTest driver doesn't support any - ignoring` output over and over again in their test suite w/ the fix:
> 
> ```
> Capybara.configure do |config|
>     config.default_set_options = { clear: :backspace }
>   end
> ```

Yeah, I'm seeing this issue. Unfortunately, there doesn't seem to be a way to either exclude that 'warning' or set `default_set_options` on a per-driver basis (as it appears to be a session-level setting).

It can be set on a per-`fill_in` basis, but either you need to do that everywhere or only on fields you've identified as flaky :sob:

**Comment by rylanb** [comment] 2023-01-24 17:27
My rails helper file has: 

```
config.before(:each, type: :system) do
    driven_by :rack_test
    
    Capybara.default_set_options = nil # Rack::Test doesn't accept options passed to Node#set
end

config.before(:each, js: true, type: :system) do
  driven_by :headless_chrome
  # address a bug where sometimes fill_in text is appended rather than replacing existing values:
  # https://github.com/teamcapybara/capybara/issues/2419
  Capybara.default_set_options = { clear: :backspace }
end
```

The warning is likely because standard Rack tests w/o JS don't allow for the `clear: :backspace` setting, which would make sense as those are simpler tests w/o the headless (or full) browser.

**Comment by N0xFF** [comment] 2023-02-10 10:12
After updating `selenium-webdriver` from `4.4.0` to `4.8.0` we have encountered the same issue and this helps:

```ruby
Capybara.default_set_options = { clear: :backspace }
```
